#! /bin/sh
# Start on startup
sxhkd &

# Monitor/Video configs
bspc monitor HDMI1 -d 1 2 3 4 5
bspc monitor eDP1 -d 6 7 8 9 10
xset -dpms
xset s off

# Bspwm configs
bspc config border_width         2
bspc config window_gap          22
#bspc config active_border_color \#817F7F
bspc config normal_border_color \#817F7F
bspc config focused_border_color \#00FF73

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
 
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# More start on startup
xsetroot -cursor_name left_ptr &
numlockx toggle &
feh --bg-fill /home/$USER/dotfiles/wallpapers/dxkzdqmytov01.png
setxkbmap br
polybar example &
picom
