#! /bin/sh
# Start on startup
sxhkd &
compton &

# Monitor configs
xrandr --output HDMI1 --mode 1920x1080 --primary --right-of eDP1

bspc monitor HDMI1 -d 1 2 3 4 5
bspc monitor eDP1 -d 6 7 8 9 10

# Bspwm configs
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a terminator floating=on

# More start on startup
feh --bg-fill ~/Pictures/minimal-sunset-landscape-4k-w5-3840x2160.jpg
polybar example
